# -*- coding: utf-8 -*-
"""Edututor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhT-yRPSYt9tlc_bFNo1ip_IwmSJTi0Q
"""

!pip install transformers torch gradio -q

import gradio as gr

# Simple EduTutor AI without heavy model
def tutor_ai(question):
    if "probability" in question.lower():
        return "Probability is the measure of how likely an event is to happen. For example, the probability of getting heads in a coin toss is 1/2."
    elif "python" in question.lower():
        return "Python is a high-level programming language used in data science, AI, and web development."
    else:
        return "I am EduTutor AI 🤖. You asked: " + question

iface = gr.Interface(fn=tutor_ai, inputs="text", outputs="text", title="EduTutor AI")
iface.launch(share=True)